spring:
    application:
        name: productsapp
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
        # For File based storage
        #url: jdbc:h2:file:/data/demo
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect